// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wcyrxudkfbptxuboabkq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndjeXJ4dWRrZmJwdHh1Ym9hYmtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MzU5OTcsImV4cCI6MjA2OTMxMTk5N30.j4_9XQJN-Dm7mRZaEreHqWllQ_Xd8OUC5Ie6BOmr7g4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});